name: Static analysis with clj-kondo
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Clj-kondo
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        clj-kondo: 2024.03.13

    - name: Install dependencies
      run: clj -e :download-deps

    - name: "Clj-kondo: show version"
      run: clj-kondo --version

    - name: "Clj-kondo: lint"
      run: clj-kondo --fail-level error --lint src test
